project:
  type: default
  output-dir: build

bibliography: references.bib

execute:
  enabled: true

format:
  revealjs:
    slide-number: c
    menu:
      numbers: true
    chalkboard: true
    scrollable: true
    preview-links: false
    view-distance: 10
    mobile-view-distance: 10
    auto-animate: true
    auto-animate-easing: ease-in
    auto-animate-duration: 0.5
    css: custom.css
    auto-play-media: true
    code-overflow: wrap
    highlight-style: atom-one
    from: markdown+emoji   # enable emoji support
    mermaid:
      theme: neutral
      fontFamily: arial
      curve: linear
    title-slide-attributes:
      data-background-color: "#ffffff"
      data-background-video: "img/title-slide-animation-bottom-light.mp4"
      data-background-video-loop: true
      data-background-video-muted: false
      data-background-size: "cover"
      data-background-opacity: "0.8"
